- tethys_portal/middleware.py
@swainn @sdc50 
We are having an issue on apps.hydroshare.org: HydroShare users login apps.hydroshare.org tethys server through OAuth, tethys will create a native tethys user and associate it with the HydroShare social account. If users try to disconnect the native tethys user from HydroShare social account, it will raise a NotAllowedToDisconnect exception, which results in a 500 error. 
I am guessing this is because the native tethys user created by HS OAuth is somehow different from the regular tethys user that was originally created via sign-up page and then got associated with HydroShare social account. At least the former user has no native tethys password, so it is useless without a HydroShare social account.
This patch handles the NotAllowedToDisconnect exception and displays a …
> handle NotAllowedToDisconnect exception

- tethys_apps/templates/tethys_apps/app_base.html
- tethys_gizmos/gizmo_options/message_box.py
1. Added block after_app_content to app base template for Modals & added instruction to modal gizmo
2. Upgraded Bootstrap from 3.2.0 to 3.3.7 in app base template
> block after_app_content

- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
Recent commits broke my app because I don't define an MVDraw object, since I don't need drawing on my map. The javascript was trying to assign fill_color, line_color, and point_color from a m_draw_options object, but that object was undefined. I propose the following to fix the bug.
> fix default draw layer styles on map view

- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
Removed ServerVector vector source and revamped all the supported sources. Need to come up with more robust support for ol.formats to more adequately support ol.source.Vector. Fixes 264.
> tethys-264 MapView - ServerVector does not exist

- tethys_gizmos/gizmo_options/map_view.py
- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
Example usage:
```python
gauge_layer = MVLayer(
source='GeoJSON',
options=feature_collection,
legend_title=legend_title,
feature_selection=True,
legend_classes =[
MVLegendClass('point', value=legend_title, fill=point_color),
],
layer_options={'style': {'image':
{'circle': {'radius': 4,
'fill': {'color': point_color},
'stroke': {'color': '#ffffff' ,
'width': 0},
}
}
}
}
)
```
> added style modification ability from mapview gizmo

- tethys_apps/app_installation.py
Symbolic Links now work on windows. Only caveat is that you need to run tethys_cmd.bat file as an administrator.
> Enable symbolic link on windows. Only works for admin.

- tethys_portal/views/__init__.py
- tethys_portal/views/receivers.py
- tethys_portal/views/user.py
This PR addressed issue #331 .
1) A receiver (event callback) runs to create a API token once a new USER object is saved to DB
2) APT Token is visible (read-only) on both User profile's view page and edit page
> 331-Create-APT-Token-for-new-USER-object

- tests/unit_tests/test_tethys_apps/test_cli/test__init__.py
- tethys_apps/cli/__init__.py
Mimic Python 2 behavior (show help text) in Python 3 when "tethys" command called with no arguments. Python 3 was throwing and error under these conditions.
Fixes #356
> Fix for tethys cli in Python 3

- docs/tethys_sdk/jobs.rst
- docs/tethys_sdk/jobs/basic_job_type.rst
- docs/tethys_sdk/jobs/condor_job_description.rst
- docs/tethys_sdk/jobs/condor_job_type.rst
- docs/tethys_sdk/jobs/condor_workflow_type.rst
- tests/unit_tests/test_tethys_compute/test_job_manager.py
- tethys_compute/job_manager.py
- tethys_compute/models.py
- tethys_sdk/jobs.py
Update docs to deprecate `JobTemplate` and provide examples using the way to create jobs without templates.
Closes #367
> Update jobs api docs

- tethys_gizmos/gizmo_options/cesium_map_view.py
- tethys_gizmos/views/gizmo_showcase.py
Found an issue with hard coding the default version of Cesium and using their CDN. When they release a new update, the old version is removed from the CDN, breaking the Cesium Map View gizmo. Instead, we will have the gizmo use the latest build version.
> Cesium gizmo bug fix

- tethys_apps/cli/scaffold_templates/app_templates/default/.gitignore
Stops tracking the .idea folder created in the git repo of a new app by adding it to the .gitignore scaffold template
> add .idea/ to gitignore scaffold template

- Dockerfile
- tests/unit_tests/test_tethys_apps/test_cli/test_gen_commands.py
- tests/unit_tests/test_tethys_apps/test_cli/test_manage_commands.py
- tethys_apps/cli/__init__.py
- tethys_apps/cli/gen_commands.py
- tethys_apps/cli/manage_commands.py
- tethys_compute/migrations/0003_auto_20190506_1714.py
* Handles data migration for migration added in #423.
* Removes makemigrations from syncdb command
* Adds tethys_port to optional argument for gen command, instead of getting it from environment.
> Fix for Issue 431 and Tweaks to Gen Command

- docker/salt/tethyscore.sls
tethyscore.sls includes a call to `tethys db configure`, but does not pass in the default username/pass from the environment, meaning that the hardcoded defaults are used instead. This means that changing the default username/password elsewhere will cause the setup to fail.
> Add normal user to `db configure` command in salt

- Dockerfile
It appears that a recent update changed the setup to install rather than develop. This breaks downstream assumptions about where files (such as `settings.py`) exist.
> Change tethys install method back to develop

- docker/run.sh
When the DB and App are started together, the salt scripts will frequently outpace the DB startup, causing a number of steps to report success when they actually failed. This change adds an (up to) 2 minute delay during which the app will poll for the database. If, after two minutes of searching, the DB is still not ready, the script will exit.
> Add check for DB before running salt scripts

- Dockerfile
- tests/unit_tests/test_tethys_cli/test_db_commands.py
- tethys_cli/db_commands.py
See: https://github.com/saltstack/salt/issues/54755
> Pin salt to 2019.2.0 until they resolve issues with 2019.2.1.

- docs/tethys_sdk/gizmos/map_view.rst
- tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_cesium_map_view.py
- tests/unit_tests/test_tethys_gizmos/test_views/test_gizmo_showcase.py
- tethys_gizmos/gizmo_options/cesium_map_view.py
- tethys_gizmos/gizmo_options/map_view.py
- tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
- tethys_gizmos/templates/tethys_gizmos/gizmo_showcase/cesium_map_view.html
- tethys_gizmos/templates/tethys_gizmos/gizmos/cesium_map_view.html
- tethys_gizmos/views/gizmo_showcase.py
- Added cesium token parameter
- Updated the URL for cesium dependencies
- Changed layers and entities to take lists
- Updated the default version of cesium to 1.63.1
- Added support for GeoJSON entities
- Added support for TileWMS and ImageWMS to MVLayers for layers
- Added support for GeoJSON to MVLayers for entities
- Added a GeoJSON example for cesium to the gizmo showcase
- Added input of cesium token to the gizmo showcase
> Fixes for cesium map views

- .travis.yml
- setup.cfg
* @msouff discovered that Coveralls has not been updated since November.
* The lines were inadvertently removed when refactoring the meta.yaml generation.
* Adds coveralls call back in.
* Changes version of master branch from 3.0.0 to 3.1.0
> Add coveralls call back to CI

- docs/installation/production/ssl_config.rst
it took me a while to figure this one out. i forgot the production install had me use this firewall utility. I think it would be wise to have the SSL instructions mirror the standard http instructions so save confusion like this.
> add example code for opening ssl port

- tethys_portal/urls.py
Django changed the way arguments are passed into class-based views when using the .as_view() method. The parameter success_url needs to be set for this functionality to work properly. This functionality has been tested using a local_only configuration of postfix.
> Password Recovery URI - Hotfix

- environment.yml
- setup.cfg
* Environment in release is configured in such a way that Bokeh allows major upgrades.
* Pin Bokeh to version 1.4.0 for the 3.0 release.
> Pin Bokeh to Version that works with 3.0

- .gitlab-ci.yml
- Dockerfile
- docker/docker-compose.yml
- docker/run.sh
- docker/salt/post_app.sls
- docker/salt/pre_tethys.sls
- docker/salt/tethyscore.sls
- docker/salt/top.sls
- docker/test-docker.sh
- tests/unit_tests/test_tethys_cli/test__init__.py
- tests/unit_tests/test_tethys_cli/test_gen_commands.py
- tests/unit_tests/test_tethys_cli/test_install_commands.py
- tethys_apps/utilities.py
- tethys_cli/db_commands.py
- tethys_cli/docker_commands.py
- tethys_cli/gen_commands.py
- tethys_cli/install_commands.py
- tethys_gizmos/templatetags/tethys_gizmos.py
* Adds additional options to run.sh script to allow it to be run in different modes (no daemon, test, etc.) to facilitate testing.
* Adds --no-db-sync option to the install command to allow for installing apps without the database sync portion (helpful in Docker builds that have no database)
* Adds pre_tethys.sls and post_app.sls scripts and simplifies tethyscore.sls, accordingly.
* pre_tethys.sls - syncs persisted configuration files that have been persisted in tethys_persist directory to appropriate locations
* post_app.sls - persists configuration files and runs post app installation steps (collectstatic and collectworkspaces)
> Improve Docker Build and Extendability

- Dockerfile
The version of Salt we were using in the Dockerfile was pinned 2 years ago due to an issue that had not been resolved on their end. This version is no longer available, which causes the build to fail. So this PR removes it. Here's to hoping the new version works.
> Remove Salt pin

- tests/unit_tests/test_tethys_apps/test_management/test_commands/test_pre_collectstatic.py
- tethys_apps/management/commands/pre_collectstatic.py
- tethys_cli/manage_commands.py
Changes:
- Changed the `tethys manage collectstatic` command to copy the static directory of apps to STATIC_ROOT by default instead of link.
- Can still use link option by providing the `--link` option: `tethys manage collectstatic --link`
Motivation: 
1. When installing on CentOS with SELinux enforcing, it is easiest to keep all static files in the web directory (`/var/www`) b/c it is already configured to allow access to files from HTTP applications. However, if the files are linked, to somewhere outside of that directory, then you'll hit the SELinux permissions wall.
2. All other static files from Tethys are copied, not linked, per the Django `collectstatic` command. This will make app static directories in STATIC_ROOT consistent with the other static directories.
> Collectstatic Copy App Static Dirs Instead of Link

- docs/installation/production.rst
- docs/installation/production/configuration/basic/supervisor.rst
- docs/tutorials/google_earth_engine/part_2.rst
- docs/tutorials/google_earth_engine/part_3.rst
* Added clarification for creating the directory for the process files (e.g.: /run/asgi) to the Supervisor Configuration doc.
* Adds links to the YouTube playlists for the Google Earth Engine Tutorial and Production Installation Guide.
> Clarification to Create /run/asgi Dir if Applicable

- docs/tethys_portal/configuration.rst
- tests/unit_tests/test_tethys_portal/test_middleware.py
- tests/unit_tests/test_tethys_portal/test_settings.py
- tethys_portal/middleware.py
- tethys_portal/settings.py
- tethys_portal/templates/mfa_email_token_template.html
- tethys_portal/templates/registration/password_reset_email.html
- Allow users to authenticate with SSO when MFA_REQUIRED is enabled but they don't have MFA enabled yet.
- Allow users to view and edit their User profile when MFA_REQUIRED is enabled but they don't have MFA enabled yet.
- Allow captcha URLs to work when MFA_REQUIRED is enabled but MFA isn't enabled yet.
- Adds two additional settings to allow for customization of MFA_REQUIRED behavior:
- SSO_MFA_REQUIRED - when True, requires users logged in with SSO to enable MFA when MFA_REQUIRED is True. Defaults to False.
- ADMIN_MFA_REQUIRED - when True, admin/staff users are required to enable MFA when MFA_REQUIRED is True. Defaults to True.
- Fixes a Typo in the documentation (default value of AXES_ONLY_USER_FAILURES was wrong).
- Removes the username from the email templates to comply with …
> Tweaks to MFA Recent Implementation

- tests/unit_tests/test_tethys_portal/test_middleware.py
- tests/unit_tests/test_tethys_portal/test_views/test_user.py
- tethys_portal/middleware.py
- tethys_portal/templates/tethys_portal/user/profile.html
- tethys_portal/views/user.py
* Don't redirect to the MFA configuration screen if MFA is required and a valid API token is used in the request.
* Hide API token on user profile until MFA is setup when MFA is required.
> Changes to MFA_REQUIRED to Account for Token Authenticated API Calls

- Dockerfile
- docker/docker-compose.yml
- docker/salt/tethyscore.sls
- docs/installation/production/additional/official_docker.rst
- docs/installation/production/configuration.rst
- docs/installation/production/configuration/advanced/django_channels_layer.rst
- docs/tutorials/websockets.rst
- tests/unit_tests/test_tethys_cli/test__init__.py
- tethys_cli/gen_commands.py
Added channel layer documentation
- InMemoryChannelLayer should be mainly used in dev
- RedisChannelLayer is the reconmmended one for production
Changed default ASGI processes parameter to 1. No point on having it be 4 when the InMemoryLayer doesn't support more than 1. This and how to set up the a redis layer are the main things explained in the documentation.
> CHANNEL_LAYERS documentation + ASGI processes default 1

- tests/unit_tests/test_tethys_apps/test_admin.py
- tethys_apps/admin.py
- tethys_quotas/admin.py
The issue was caused by how we added the custom Quota's fields to the change/edit User admin form:
```python
class CustomUser(UserAdmin):
def change_view(self, *args, **kwargs):
self.inlines = [UserQuotasSettingInline]
return super().change_view(*args, **kwargs)
```
Changing `self.inlines` for the `change_view` of the `UserAdmin` form permanently changed it for all views including the `add_view`, which would cause the error. I'm guessing this is because `self.inlines` is a class property.
The fix was to remove the `UserQuotasSettingInline` for the `add_view`:
```python
class CustomUser(UserAdmin):
def add_view(self, *args, **kwargs):
if UserQuotasSettingInline in self.inlines:
self.inlines.pop(self.inlines.index(UserQuotasSettingInline))
return super().add_view(*args, **kwargs)
def …
```
> Fix for Issue 592

- tethys_apps/admin.py
This was causing erroneous migrations to be generated for the mfa and auth Django apps. See #610
> Remove the User_Keys change to auth to prevent erroneous migrations.

- docs/installation/update.rst
Change upgrade instructions to recommend using `conda install` instead of `conda update`.
> Update Upgrade Instructions

- tethys_gizmos/gizmo_options/jobs_table.py
* Introducing the TethysJob model import at the module level of the JobsTable causes some issues for our testing. We split our tests into integrated and unittests. Unittests run without needing Tethys started up. However, all of our unittest tests that use a Gizmo of any sort started failing b/c all gizmos are imported in the tethys_sdk.gizmo module.
* I recommend moving TethysJob model import out of module scope in jobs_table.py and into the function scopes where it is used.
> Jobs Table Bug Fixes

- tests/unit_tests/test_tethys_portal/test_views/test_user.py
- tethys_portal/templates/tethys_portal/user/profile.html
- tethys_portal/views/user.py
I had to implement the logic check in the controller, rather than the template as @ezrajrice suggested b/c the templating syntax doesn't support parenthesis. I also added four new test cases to cover all combinations of had_mfa and mfa_required so we can catch this issue in the future if it occurs.
> Fixes Issue #626

- tethys_services/backends/arcgis_portal.py
The ArcGIS Rest API for OAuth supports using the refresh_token, so it should be included in EXTRA_DATA so that it can be used to refresh a soon-to-be-stale session. See https://developers.arcgis.com/rest/users-groups-and-items/token.htm
> Override EXTRA_DATA to include refresh_token

- tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_map_view.py
- tethys_gizmos/gizmo_options/map_view.py
- tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
Add support for specifying a list of time steps in the MVLayer to be used to implement animations for time-enabled layers.
Implemented support in the CesiumMapView for now. Not supported in the main MapView as of yet.
> Add Support for Time-Enabled Layers in Cesium

- docs/installation/production/configuration/advanced/social_auth.rst
The documentation for OneLogin contained a typo and needed clarification:
* The login URL for Tethys is `http://<SERVER_DOMAIN_NAME>/accounts/login/`, not `http://<SERVER_DOMAIN_NAME>/login/`
* The 'SUBDOMAIN' parameter is the full protocol and domain, not just the subdomain prefix (`"https://example.onelogin.com"` NOT just `"example"`).
> Add clarifications and fix typos for onelogin SSO instructions

- environment.yml
BYU is experiencing issues where installing Dev builds installs Channels 3.*, which breaks Tethys. This PR pins the channels dependency to 2.* for now.
> Pin Channels to 2.*

- environment.yml
Pin psycopg2 to < 2.9 b/c 2.9 doesn't work with Django 2.2. See #698
> Fix for Issue #698

- tests/unit_tests/test_tethys_apps/test_models/test_SpatialDatasetServiceSetting.py
- tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_date_picker.py
Two tests were still using `import mock` instead of `from unittest import mock`. They only recently started failing, so we must have been getting the mock package installed through some other package. This PR changes both import appropriately.
> Remove left over "import mock" statements from tests.

- tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_plotly_view.py
The test of the Plotly Gizmo was failing because the new version of Plotly changed how the HTML was rendered slightly (spaces were removed in series arrays when they are serialized).
> Fix Plotly Gizmo Test

- tethys_gizmos/gizmo_options/map_view.py
- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
There are very likely other compatibility issues that would need to be addressed if we truly wanted Tethys Core robust enough to allow for ANY version of OpenLayers. But I only quickly came upon and addressed the one issue with "ol.inherits".
> Updates ol CDN URL and fixes 1 compatibility issue

- tethys_apps/static/tethys_apps/js/app_base.js
- tethys_apps/static/tethys_apps/js/feedback.js
- tethys_apps/templates/tethys_apps/app_base.html
- tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
This moves the retrieving of the CSRF token from an AJAX call to having be embedded in the page in a script tag. It also moves code from multiple places into the app_base.js file, so it's only in one place.
> Simplify/secure CSRF token ajax handling

- tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
When Cesium is loaded via ajax then it needs to be re-initialized. This adds a `reInitializeMap` to the public interface (mirroring the call on the `tethys_map_view`).
> Add API to initialize Cesium

- docs/installation/production/configuration/advanced/https_config.rst
* Adds Certbot instructions to HTTPS config tutorial for production docs
* Fixes #733 
View a live version of this docs update here: http://docs.tethysplatform.org/en/cloud-images-docs/installation/production/manual/configuration/advanced/https_config.html
> Updates HTTPS docs with Certbot instructions

- .github/workflows/tethys.yml
- tests/unit_tests/test_tethys_cli/test_app_settings_command.py
- tethys_apps/utilities.py
- tethys_cli/app_settings_commands.py
- tethys_cli/services_commands.py
- Adds type option to `tethys services create spatial` command to allow specifying GeoServer or THREDDS engine.
- Add support for setting custom settings via the `tethys app_settings` command.
- Also fix a couple issues with CI not running coveralls or the builds during PRs
> Updates to Services and App Settings CLI

- tests/unit_tests/test_tethys_cli/test_docker_commands.py
- tethys_cli/docker_commands.py
Updates the Docker command to use new versions of the THREDDS and GeoServer container images that have been patched for log4j vulnerabilities.
> Patch docker cli to use log4j-patched versions of geoserver and thredds

- docs/installation/production/cloud.rst
- docs/installation/production/docker.rst
The development of the new Docker and Azure production deployment documentation was sponsored by SERVIR. This PR adds appropriate attribution to those pages of the docs.
It also adds links to supplementary presentations that can be used as primer material when training on these topics.
> Add links to presentations and attribution to Docker and Azure Production docs

- docs/tutorials/google_earth_engine/part_3/service_account.rst
This is something that I discovered while installing apps that uses google earth engine in production. If the first authentication is done with an old version of the earthengine-api, it may give a 404 error for the authentication.
> Addition of note for the first authentication process.

- tests/unit_tests/test_tethys_apps/test_base/test_controller.py
- tethys_apps/base/controller.py
- tethys_cli/scaffold_templates/app_templates/default/tethysapp/+project+/controllers.py_tmpl
- tethys_cli/scaffold_templates/extension_templates/default/tethysext/+project+/__init__.py
This PR addresses issue #789 as follows:
* Fixes the import for the controller decorator in the app scaffold template
* Prints a warning and traceback for import errors that are not ModuleNotFoundErrors encountered while registering controllers:
> Fixes Bad Import in App Scaffold

- docs/tethys_sdk/layouts/map_layout.rst
- tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_map_view.py
- tethys_gizmos/gizmo_options/map_view.py
- tethys_layouts/mixins/map_layout.py
- tethys_layouts/static/tethys_layouts/map_layout/map_layout.css
- tethys_layouts/static/tethys_layouts/map_layout/map_layout.js
- tethys_layouts/views/map_layout.py
This PR contains several fixes for bugs discovered during preparation for the AWRA Tethys Platform presentation.
- Set geometry attribute on GeoJSON MVLayers automatically. To silence warning that happens when using Map Layout.
- Make get_feature_id_from_feature smarter in map_layout.js Don't assume GeoServer layer.
- Fix scroll issue on map layout on smaller screens
- Pass the request and args and kwargs to MapLayout.get_plot_for_layer_feature() Allows it to recieve the app_workspace when class is decorated.
- Add tests for MVLayer changes
> Tethys Map Layout Fixes

- tests/unit_tests/test_tethys_cli/test_scaffold_commands.py
Patching the built-in `callable` function using the decorator was causing an infinite recursion error on the scaffold command tests.
Interestingly, patching using context manager worked fine...
This PR refactors the tests to not mock `callable` at all.
> Fix for failing scaffold command tests in Python 3.10.6

- docs/tethys_cli.rst
- docs/tethys_sdk/app_class.rst
- docs/tethys_sdk/workspaces.rst
- tests/unit_tests/test_tethys_apps/test_base/test_app_base.py
- tests/unit_tests/test_tethys_apps/test_base/test_workspace.py
- tethys_apps/base/app_base.py
- tethys_apps/base/bokeh_handler.py
- tethys_apps/base/workspace.py
- tethys_apps/utilities.py
- tethys_quotas/decorators.py
- tethys_sdk/workspaces.py
Adds `get_app_workspace` and `get_user_workspace` functions that can be used when the decorator cannot be used. 
- These functions will enforce Workspace Quotas when enabled.
- They raise an Assertion Error when the Quota is not met.
> Add get_workspace utility functions that enforce quotas

- docs/tethys_sdk/layouts/map_layout.rst
- tests/unit_tests/test_tethys_layouts/test_views/test_map_layout.py
- tethys_layouts/mixins/map_layout.py
- tethys_layouts/static/tethys_layouts/map_layout/map_layout.js
- tethys_layouts/views/map_layout.py
Include the `layer.tethys_data` and `feature.properties` objects in the AJAX request that is sent to generate the plot data.
TODO:
> Refinements to the Click-n-plot capability of MapLayout

- tests/unit_tests/test_tethys_apps/test_models/test_TethysApp.py
- tethys_apps/base/app_base.py
- tethys_apps/models.py
- tethys_layouts/views/map_layout.py
Fixes a bug with app setting syncing introduced with #890.
- Persistent store database settings that were created dynamically using the `app.create_persistent_store()` method were removed every time Tethys reloaded.
- This is because dynamically created settings are not listed in the app.py and were thus being treated as obsolete settings.
- This PR makes it so that settings with a `dynamic` attribute that is `True` will be ignored when removing obsolete settings.
> Fixed dynamic settings sync bug

- tests/unit_tests/test_tethys_layouts/test_views/test_map_layout.py
- tethys_portal/dependencies.py
Fix the "min" path for cookies.js so it will work with CND and local.
The published path for the minified version of the `cookies.js` file in the npm package is `cookies_min.js`. JSDelivr generated it's own version and called it `cookies.min.js`. Since Tethys used the `cookies.min.js` path, the minified version would work when using CDN, but it would fail when trying to server the files locally (because the npm package didn't contain the `cookies.min.js` version of the file.
This fix changes the minified path to use `cookies_min.js` which is available in both the npm package and on JSDelivr.
> Fix Cookies JS Path

- docs/installation.rst
URL to Mamba docs is entered using Markdown syntax and not rendering properly.
> Fix Mamba URL in Installation Docs

- tethys_gizmos/views/gizmos/jobs_table.py
Before this change, an exception while deleting a job would show the error message in a green success box and remove the job row from the browser display, although a browser refresh would show that job again. After this change, it will show the error in a red box and still display the job.
> Fix error message showing in green box while deleting a job

- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
Fix the javascript so that on a workflow that adds points, if you go to the next page, but then go back to the previous page (where the point was added), you get the points displayed again.
> Fix for workflows when you add a point and go back

- tethys_apps/migrations/0002_auto_20230407_2337.py
Fixes the missing trigger problem:
```
Running migrations:
Applying tethys_apps.0002_auto_20230407_2337...Traceback (most recent call last):
File "/home/user/miniconda3/envs/tethys/lib/python3.10/site-packages/django/db/backends/base/base.py", line 242, in _commit
return self.connection.commit()
psycopg2.errors.InternalError_: could not find trigger 21935
bash```
> Fixed migration with apps that use ATCORE.

- docs/tutorials/thredds/thredds_primer.rst
- tests/unit_tests/test_tethys_cli/test_docker_commands.py
- tethys_cli/docker_commands.py
This PR fixes #938 by:
- Updating the default thredds image tag to "5.4" (current release)
- Adding the image name and tag options to the docker command to allow users to override the defaults we provide:
```bash
tethys docker init -c thredds -i "tethysplatform/thredds-docker" -t 4.6.20-SNAPSHOT
```
> Add Docker Image Name and Tag Options to Tethys Docker Command

- tests/unit_tests/test_tethys_cli/test_scheduler_commands.py
- tethys_cli/scheduler_commands.py
Implements #907
* Adds `-o/--port` option to the `tethys scaffold create-condor` command
* Includes the `port` attribute in the `tethys scaffold list -t condor` command output
> Add Port Option to tethys scheduler create-condor CLI command

- tethys_layouts/static/tethys_layouts/map_layout/map_layout.js
- tethys_sdk/static/tethys_sdk/js/utilities.js
- The WMS layer feature selection feature would hang when more than 2 layers were involved in the selection. This was due to nested loops using the same looping variable (`i`). This PR fixes the issue by renaming the variable in the outer loop.
- This PR also updates deprecated `autoPan` properties of `ol.Overlays`.
> Fix for Feature Selection Hang on MapView Gizmo

- tethys_apps/base/bokeh_handler.py
I'm not sure why I added these, but I can't think of how they would ever be used and it turns out that it messes up the URL registration and requires that `args` and `kwargs` be passed in as URL variables.
> Hotfix - remove args and kwargs from default Bokeh controller

- environment.yml
- tests/unit_tests/test_tethys_cli/test_install_commands.py
- tethys_cli/install_commands.py
> Fix Custom JSON setting error when installing from file

- Dockerfile
This pull request addresses an issue with the salt-minion package not being found during the Docker build, causing it to fail.
> Fix for Failing Docker Build

- tethys_portal/settings.py
Replaced deprecated setting `AXES_ONLY_USER_FAILURES` with recommended setting `AXES_LOCKOUT_PARAMETERS = ['username']`.
> Replace deprecated Django Axes setting

- tests/unit_tests/test_tethys_portal/test_settings.py
- tethys_portal/settings.py
bokehjsdir() has been deprecated in favor of bokehjs_path()
Using bokehjsdir() now causes an error when running docker build
https://github.com/bokeh/bokeh/blob/69c084e692d79632c97ea1cfc5ceb10d0217e6f4/src/bokeh/settings.py#L779
> bokehjsdir() has been deprecated in favor of bokehjs_path()

- tests/unit_tests/test_tethys_services/test_backends/test_hydroshare.py
@swainn, @shawncrawley, This fixes a test for compatibility with the latest version of `social-auth-core`. We need to get this merged so that the tests will pass for all of the other PRs.
The library made a seemingly innocuous change:
from:
```python
value = response.get(name) or details.get(name) or details.get(alias)
```
to:
```python
value = response.get(name, details.get(name, details.get(alias)))
```
The problem was that in the first case the `details.get` would not get evaluated unless `response.get(name)` returned `None`. Whereas in the second case it gets evaluated regardless. In our test we had a mock response with a `name` attribute, but we were not passing `details`.
> Fix test for social auth v4.5.4

- Dockerfile
> ARG build variables: django, channels, daphne

- tests/unit_tests/test_tethys_apps/test_decorators.py
- tests/unit_tests/test_tethys_apps/test_urls.py
- tests/unit_tests/test_tethys_apps/test_utilities.py
- tests/unit_tests/test_tethys_cli/test_app_settings_command.py
- tests/unit_tests/test_tethys_cli/test_list_commands.py
- tests/unit_tests/test_tethys_config/test_context_processors.py
- tests/unit_tests/test_tethys_layouts/test_views/test_map_layout.py
- tests/unit_tests/test_tethys_portal/test_asgi.py
- tests/unit_tests/test_tethys_portal/test_context_processors.py
- tests/unit_tests/test_tethys_portal/test_utilities.py
- tests/unit_tests/test_tethys_portal/test_views/test_accounts.py
- tests/unit_tests/test_tethys_portal/test_views/test_api.py
- tests/unit_tests/test_tethys_portal/test_views/test_user.py
- tests/unit_tests/test_tethys_services/test_backends/test_hydroshare.py
- tethys_apps/decorators.py
- tethys_apps/urls.py
- tethys_apps/utilities.py
- tethys_config/context_processors.py
- tethys_portal/context_processors.py
- tethys_portal/templates/header.html
- tethys_portal/templates/tethys_portal/user/user_header_menu.html
- tethys_portal/utilities.py
- tethys_portal/views/accounts.py
- tethys_portal/views/api.py
- tethys_portal/views/user.py
This PR looks to resolve https://github.com/tethysplatform/tethys/issues/1042. The issue is that there are many redirects and reverses that point to a hardcoded "home" url. While this works fine when the single app index is home, these redirects fail when an app index is not "home". 
The PR resolves the issue by putting conditional logic in front of the hardcoded "home" redirects. If the tethys portal is in single app mode, then the "home" redirects will point towards the app index url instead. 
Along with the hardcoded "home" fix, I have also updated additional redirects that point to the app_library url which is no longer available in standalone app mode. If the tethys portal is in single app mode, these old app_library redirects will point to more appropriate endpoints instead. 
This …
> Standalone App Non-Home Index Fixes

- tests/unit_tests/test_tethys_layouts/test_mixins/test_map_layout.py
- tethys_layouts/mixins/map_layout.py
Added option to include a CQl filter when building a WMS layer, by adding it to the params dict used to build the layer.  This can be uesd to filter a layer based on an attribute, filter function, geometric filter, etc.
> Added CQL (Common Query Language) filter for building WMS layers.

- .github/workflows/tethys-release.yml
- .github/workflows/tethys.yml
This merge request addresses warnings that have cropped up in the CI do to deprecation of Node.js v16
- Update CI to use actions/checkout@v4
actions/checkout [version history](https://github.com/actions/checkout/releases)
This task was first noted when creating the build matrix for Tethys.
> Fix Deprecation Warnings in CI

- .github/workflows/tethys-release.yml
- .github/workflows/tethys.yml
This merge request addresses finishing fixing warnings that have cropped up in the CI do to deprecation of Node.js v16
- Update CI to use actions/checkout@v4
actions/checkout [version history](https://github.com/actions/checkout/releases)
This finishes the fixes that @swainn merged earlier today.
> Finish Fixing CI Deprecations

- .github/workflows/tethys.yml
- Dockerfile
- scripts/install_tethys.sh
This merge request addresses an issue where running the install script didn't pin to a specific version of python or Django. It was only setting the lower bounds. We want to pin it when we set a version.
- Update the install script to set version to be `==` rather than `>=`
- Fix python version flag to be `-p` rather than `-v` to match usage notes
- Update the docker file to `sed` the python version correctly
- None
- This was found when trying to update the `tethysext-atcore` dockers.
> Fix Matrix Issue with Pinned Versions

- tethys_compute/models/dask/dask_scheduler.py
Introduced in #967, f863b48, tethys_compute/models/dask/dask_scheduler.py , the changed code has lowercase `client` instead of `Client`, which imports the module instead of the class, resulting in a  `TypeError: 'module' object is not callable` error.
- `Client = optional_import("client", from_module="dask.distributed")` ➡️ `Client = optional_import("Client", from_module="dask.distributed")`
- #967
-  This bug _might_ not appear on macOS HFS+/APFS because of case-insensitive filesystems? But I'm seeing it on Windows. I'm guessing this is the case everywhere though.
> Fix Dask scheduler Client import error

- docs/conf.py
Update conf.py per RTD's recommendations. See: https://about.readthedocs.com/blog/2024/07/addons-by-default/
- Get `html_baseurl` from `READTHEDOCS_CANONICAL_URL` environment variable.
- Add `READTHEDOCS` to the `html_context`.
> Changes to conf.py in preparation for RTD Addons rollout

- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
This merge request addresses issue #998 for basemap layers with typos, or empty basemap list in mapview. Now throws warnings in console for unsupported map layer names provided.
- added 'add_default_basemap_layer' function
- added warnings in console for invalid or misspelled basemap names
None
None
- [] New code is 100% tested
- [] Code has been formated
- [] Code has been linted
- [] Docstrings for new methods have been added
> Bug Fix for issue #998

- tethys_cli/scaffold_templates/extension_templates/default/setup.py_tmpl
This merge fixes an import in the default setup.py file that is generated when scaffolding a tethys extension
> Fix in scaffold for extension

- tethys_apps/base/controller.py
This merge request addresses the previous issue with controllers using app_media, user_media, app_public, and app_resources in controller decorators causing url map errors or not being found. 
These parameters are now treated like user and app_workspace are treated in controller decorators.
Fixes #1080
> Bug Fix for Issue #1080

- tests/unit_tests/test_tethys_cli/test_db_commands.py
- tethys_cli/db_commands.py
This merge request addresses an issue with the tethys db create CLI command. The issue occurs when multiple portals are trying to share a single database with the same tethys_super table. If the tethys_super table already exists, then the tethys db create CLI command will try to create the tethys_super table, fail to do so, and then exit before the table for the portal is created. 
This merge request sets the exit_on_error to False for the create_db_user call inside of the create_tethys_db function. This will ensure that both create_db_user calls are executed, whether they are successful or not. To keep the same behavior currently where the create_tethys_db function can exit on an error, I have added a exit_creation_on_error argument to the function. If set to True, then the function will …
> Nonexit Tethys Create DB CLI Command

- tests/unit_tests/test_tethys_apps/test_utilities.py
- tethys_apps/utilities.py
This merge request addresses issue #1061 where the redirect for apps with no trailing / would break
- Append the slash if the there is no app to redirect to
- N/A
-  This was an issue caused in django5
- [] New code is 100% tested
> Fix URL redirect for apps with no slash

- docs/_static/css/tethys.css
- docs/installation/production.rst
- docs/installation/production/docker/docker_compose.rst
- docs/installation/production/docker/dockerfile.rst
- docs/tutorials/bokeh.rst
- docs/tutorials/thredds/plot_at_location.rst
- docs/tutorials/thredds/visualize_leaflet.rst
Update docs for docker production
Note that for the docker tutorial to work properly the following PRs need to be merged to fix other tutorial repos:
- https://github.com/tethysplatform/tethysapp-thredds_tutorial/pull/1
- https://github.com/tethysplatform/tethysapp-bokeh_tutorial/pull/3
- https://github.com/tethysplatform/tethysapp-earth_engine/pull/3
> Docker Production Docs

- .github/workflows/tethys-release.yml
- .github/workflows/tethys.yml
- tests/unit_tests/test_tethys_apps/test_models/test_PersistentStoreDatabaseSetting.py
- tethys_apps/models.py
**THIS IS A HOTFIX FOR 4.2**
In PostGIS 3, the raster functionality is moved to a separate extension: postgis_raster. This PR updates syncstores to add the raster extension if it detects PostGIS version 3.
- Syncstores command checks PostGIS version and creates the postgis_raster extension if on version 3.X when initializing a postgis database.
- CHL has requested this be released as a patch of 4.2 so their new server can get the fix.
- See: #1097
> HOTFIX: Patch to syncstores to enable support for PostGIS 3.4

- docs/tethys_sdk/jobs.rst
- tests/unit_tests/test_tethys_compute/test_models/test_TethysJob.py
- tethys_compute/models/tethys_job.py
- tethys_gizmos/gizmo_options/jobs_table.py
- tethys_gizmos/static/tethys_gizmos/css/jobs_table.css
- tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
- tethys_gizmos/templates/tethys_gizmos/gizmos/job_row.html
- tethys_gizmos/templates/tethys_gizmos/gizmos/jobs_table.html
The functionality of `update_status` and the status updating of the Jobs Table Gizmo were limited to hard-coded statuses. All custom statuses were considered to be "terminal" statuses. This PR changes the logic of the Jobs Table JS to make it more flexible with which statuses it will continue to update. It also add convenience functions for classifying custom job statuses and adds documentation to better describe custom job statuses.
- Jobs Table Gizmo JS now checks for ``TethysJob.ACTIVE_STATUSES`` rather than a list of hard coded statuses
- adds methods to classify custom statuses in the ``TethysJob`` class.
- changes the logic of the ``update_status`` method to check if ``OTH`` statuses should be updated.
> Jobs table fixes

- tethys_apps/templates/tethys_apps/app_card.html
In addition to having the app description available through the info icon on the app card, some user feedback has suggested that having the app description as a tooltip on the app card would be helpful.
This PR uses the `app.description` for the app card `title` if it's available. It also adds a `title` attribute to the app name header on the card and sets that as the `app.name`
> App description as tooltip

- docs/docs_environment.yml
- docs/installation/production/manual/configuration/basic/file_permissions.rst
- docs/installation/production/manual/configuration/basic/supervisor.rst
- docs/tethys_sdk/jobs.rst
- tests/unit_tests/test_tethys_apps/test_views.py
- tests/unit_tests/test_tethys_compute/test_tasks.py
- tests/unit_tests/test_tethys_compute/test_views/test_update_status.py
- tests/unit_tests/test_tethys_gizmos/test_views/test_gizmos/test_jobs_table.py
- tests/unit_tests/test_tethys_portal/test_urls.py
- tethys_apps/views.py
- tethys_compute/tasks.py
- tethys_compute/views/__init__.py
- tethys_compute/views/update_status.py
- tethys_gizmos/views/gizmos/jobs_table.py
- tethys_portal/urls.py
Add the ability to add a query argument `delay` to the `update_job_status` callback, e.g.:
```
http://127.0.0.1:8000/update-job-status/14/?delay=120
```
The server will wait for `delay` seconds before calling `update_status` on the job.
This "delay" capability was added as a general capability, and the ability schedule periodic execution of a function was included (though not used by the `update_job_status` callback). I have not added this to the Tethys SDK because I would like to get more experience with it before deciding if it should be made "officially" available to apps. I don't consider it to be a robust task scheduling capability since all tasks are stored in memory and would be lost if the server restarts.
- modified the `update_job_status` callback to be async and to support a …
> Delayed job status

- docker/run.sh
- tests/unit_tests/test_tethys_apps/test_harvester.py
- tethys_apps/harvester.py
This merge request addresses the sqlite programming error that is triggered when harvesting apps on the method `_harvest_app_instances` on the file `tethys_apps/harvester.py`.
- `_harvest_app_instances` added exception for `sqlite3` `ProgramingError`
- Added test
> Check for Sqlite ProgramingError Exception 

- .github/release.yml
A typo in the `release.yml` file was preventing the `Feature` category from generating in the auto-generated release notes. 
Also, note that if multiple labels are applied to the same PR (e.g. `experimental` and `major feature`) then it will only match the first category.
> Fix release.yml

- Dockerfile
- tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
Fire select event in the callback of `boxend` event, so the name attribute will pop up automatically.
(Click Play button to see the gif)
> Fire select event after boxend

- tests/unit_tests/test_tethys_apps/test_base/test_controller.py
- tethys_apps/base/controller.py
fix bug preventing the url arg from being defined as a dict in routing decorators
The way the `title` value was being created in the `_get_url_map_kwargs_list` function causes a bug when the `url` argument is a `dict`. This fix addresses that bug and adds tests to catch the original error.
> Bugfix: url kwargs title

- tests/unit_tests/test_tethys_apps/test_base/test_controller.py
- tethys_apps/base/controller.py
- tethys_cli/start_commands.py
> Bugfix: fix quickstart

- docs/tethys_portal/feedback.rst
- docs/tutorials/thredds/new_app_project.rst
Removed a few instances of the old app_name:controller convention from the app.py file contents in tutorial documents
> Fixed index names in tutorial docs

- Dockerfile
Fix for issue #1132 
- Updates the Debian distribution to bookworm
- Updates the salt minion installation
> Upgrade docker to use Debian bookworm (current stable) and update salt package

- tests/unit_tests/test_tethys_compute/test_job_manager.py
- tests/unit_tests/test_tethys_compute/test_views/test_update_status.py
- tethys_apps/decorators.py
- tethys_compute/job_manager.py
- tethys_compute/views/update_status.py
- tethys_gizmos/views/gizmos/jobs_table.py
This merge request addresses anonymous users being unable to get the status of a condor job. Without this fix, the anonymous user cannot view a jobs_table gizmo that correctly refreshes the status of its jobs.
- 
- 
-
> Allow anonymous users to get condor job status

- tests/unit_tests/test_tethys_apps/test_templatetags/test_site_settings.py
- tethys_apps/templatetags/site_settings.py
This merge request addresses https://github.com/tethysplatform/tethys/issues/1127 where CSS text greater than 256 characters causes an OSError exception on many pages, including admin pages.
- On any file error, treat "var" as CSS text to embed
- Add docstring
- Reorder imports
- Remove unnecessary else: after return
- Add unit test
- https://github.com/tethysplatform/tethys/issues/1127
- While making the unit test, I found that added a /* CSS Comment */ bypassed the issue. So the test variable is a little shorter than I hoped for. Also, that test CSS is not going to win any design awards.
> Avoid "File name too long" error

- docs/installation.rst
- docs/installation/conda.rst
- docs/installation/production/manual/installation.rst
- docs/tutorials/google_earth_engine/part_2/about_page.rst
- docs/tutorials/google_earth_engine/part_2/clip_by_asset.rst
- docs/tutorials/google_earth_engine/part_3/prepare.rst
Made a small addition to tutorial instructions in the google earth engine tutorial to address an issue with creating the base folders in assets.
Fixed a missing line of highlighted code for changes to a code block in the tutorial as well.
> Small fixes for google earth engine tutorial

- tethys_portal/dependencies.py
The `css_integrity` hash for the boostrap icons JS library was not updated when the version was updated. As a result, the library won't load on secure deployments of Tethys.
The documentation for bootstrap-icons no longer provides the security hash  (see: https://icons.getbootstrap.com/#install), so this PR removes it.
- Removed the `css_integrity` argument for the `bootstrap_icons` library in `dependecies.py`
- Introduced by #1081
> Remove the css_integrity hash for bootstrap-icons dependency

- .github/workflows/tethys-release.yml
- .github/workflows/tethys.yml
- Dockerfile
The Conda build is broken and Docker images in release do not have the right version of Python in them. This pull request fixes both issues.
This merge request addresses...
- remove the ".tar.gz2" extension from conda upload glob to address change to ".conda" extension
- add the build args for python and django versions to the docker build command in tethys-release.yml
> Conda build and Docker Python Version fix

- tethys_layouts/static/tethys_layouts/map_layout/map_layout.js
When `feature_id` is a number, it doesn't have the method `includes()`, which will trigger the error ` feature_id.includes is not a function`.
> Bugfix: feature_id.includes is not a function when feature_id is a number

- docs/installation/production/docker/docker_compose.rst
- tests/unit_tests/test_tethys_cli/test_docker_commands.py
- tethys_cli/docker_commands.py
This merge request addresses that the problem caused due to image tag `5.4` for `unidata/thredds-docker` no longer being available, so it is changed to `5.6`
- change for thredds image tag from 5.4 to 5.6 on `tethys docker` command and test.
- Docs have been updated as well
> image tag 5.4 for unidata/thredds-docker no longer available

- tests/unit_tests/test_tethys_portal/test_context_processors.py
- tethys_apps/templates/tethys_apps/app_base.html
- tethys_portal/context_processors.py
- tethys_portal/settings.py
- tethys_portal/templates/base.html
- tethys_portal/templates/tethys_portal/error.html
- tethys_portal/urls.py
This PR addresses an issue with loading error templates when the middleware hasn't been processed.
The specific issue was caused by a missing host in ALLOWED_HOSTS, which would end up raising this error:
<details>
```
ERROR Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
^^^^^^^^^^^^^^^^^^^^^
File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
response = self.process_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/tethysdev/miniconda3/envs/tethys/lib/python3.12/site-pa …
```
> Terms and conditions error

- README.rst
- docs/features.rst
- docs/index.rst
- docs/software_suite.rst
- tethys_apps/base/paths.py
- tethys_compute/tasks.py
- tethys_compute/views/__init__.py
- tethys_compute/views/update_status.py
- tethys_sdk/paths.py
- tethys_utils/deprecation.py
I came across a few places where we were still referring to "water resource web apps" and where "Tethys Geoscience Foundation" was being mistakenly referred to as "Tethys Geospatial Foundation". I also changed one case of "environmental web apps" to "geoscientific web apps" for consistency.
- Docs and docstrings updated as described above.
- 
-
> Update docs/docstrings to use "geoscience" verbiage

- .github/workflows/tethys-release.yml
- .github/workflows/tethys.yml
- tests/unit_tests/test_tethys_apps/test_static_finders.py
- tethys_apps/static_finders.py
Django has updated the parameter for `find()` from `all` to `find_all`, see this [commit](https://github.com/django/django/commit/0fdcf1029cea2d43bd68c5270f48e0f7deab5e47#diff-10554987530a8268887edf216bf057d24f954d2d9364f7c71a0d70500e65a2c0L29) 
update TethysStaticFinder.find()
> update TethysStaticFinder.find() to be compatible with django5.2

- Dockerfile
- docker/build-checks.sh
The PR #1169 introduced the dependencies into the pyproject.toml to support building a PyPI package in the future. However, these changes inadvertently override the pinned versions in the Docker image that is built. This PR fixes this issue. 
- Run the pip install in the Dockerfile without installing dependencies--they are currently installed via the environment.yml.
- Change ADD to COPY commands per docker best practices
- #1169 
-  In the future we will probably want to support building the docker image using pip or UV to install dependencies instead of conda, but this patch fixes it for the current approach of using Conda.
> Fix for Pip Install Overrides Django Pinning

- tests/unit_tests/test_tethys_cli/test_db_commands.py
- tethys_apps/models.py
- tethys_cli/db_commands.py
This merge request removes `template0` as the parent database from which new databases inherit. 
- `tethys_app/models.py` change to not use `template0` when creating databases
- `tethys_cli/db_commands.py` change to not use `template0`
- None
-  This allows applications to not be bound to `template0` when creating new databases
> Removing `template0` as the parent database from which new databases inherit. 

- tethys_layouts/static/tethys_layouts/map_layout/map_layout.js
This merge request addresses the bug caused by turning off Tiling on the wms. When `TILE` is set to False  on the `build_wms_layer` function, the source becomes `ol.source.ImageWMS` on the JavaScript side. The function `getUrls` does not exists on `ol.source.ImageWMS`, but `getUrl`.
- Added some if statements:
```
let urls = [];
if (source instanceof ol.source.TileWMS) {
urls = source.getUrls();
} else if (source instanceof ol.source.ImageWMS) {
urls = [source.getUrl()];
}
```
- None
-  None
> Fix error for missing function on ol.source.ImageWMS

- docs/tethys_sdk/paths.rst
This merge request makes a few small fixes to a code block in the Paths API documentation. 
These changes correct the use of the App class's App Public and App Resources path properties in a code block.
> Documentation Fixes
