tethysplatform/tethys

docs/tethys_sdk/gizmos/map_view.rst
docs/tethys_sdk/gizmos/plot_view.rst

Added JS libraries required in main template.

AJAX Docs JavaScript import update

---

templates/tethys_portal/home.html
tethys_apps/cli/gen_templates/settings
tethys_conda_env.yml
tethys_portal/forms.py
tethys_portal/urls.py
tethys_portal/views/home.py

1.     Hide "Sign Up" button if open sign up disabled
2.     Require stronger passwords
3.     Hide admin/login page if not logged in as staff or higher (Which pretty much hides it completely).
4.     Added CAPTCHA login for protection against brute force account attacks.

Improved Security

---

tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
tethys_gizmos/views/gizmo_showcase.py
tethys_gizmos/views/gizmos/jobs_table.py

bugfix: jobs_table parse delete boolean from post

---

docs/tethys_sdk/gizmos/esri_map.rst
tethys_gizmos/gizmo_options/__init__.py
tethys_gizmos/gizmo_options/esri_map.py
tethys_gizmos/static/tethys_gizmos/js/esri_map.js
tethys_gizmos/templates/tethys_gizmos/gizmo_showcase/esri_map.html
tethys_gizmos/templates/tethys_gizmos/gizmo_showcase/index.html
tethys_gizmos/templates/tethys_gizmos/gizmos/esri_map.html
tethys_gizmos/urls.py
tethys_gizmos/views/gizmo_showcase.py

Reverts tethysplatform/tethys#222

Revert "Revert "Dev: A simple ESRI Map View GIzmo""

---

tethys_gizmos/templatetags/tethys_gizmos.py

reset gizmo_name in TethysGizmoIncludeNode in case the same node gets rendered more than once. This allows for polymorphic gizmo rendering. E.g. 
```
{% for input_options in options_list %}
{% gizmo input_options %}
{% endfor %}
```
where `options_list` is a list of different gizmo options objects.

reset gizmo_name

---

docs/conf.py
docs/installation/linux_and_mac.rst
docs/installation/windows.rst
environment_py2.yml
scripts/install_tethys.bat
scripts/install_tethys.sh

Finished Windows install script
Added some docs for Windows
Small tweaks to the Mac/Linux install script/docs
Set `html_use_smartypants` in `conf.py` to `False` so `--` would render correctly.

Install scripts update

---

docs/installation/linux_and_mac.rst
docs/installation/windows.rst
scripts/install_tethys.bat
scripts/install_tethys.sh

fix for paths with spaces on Windows and activate scripts

---

tethys_gizmos/gizmo_options/plot_view.py

Fix for #244

---

docs/installation/linux_and_mac.rst
docs/installation/windows.rst
scripts/install_tethys.bat
scripts/install_tethys.sh
tethys_apps/cli/__init__.py
tethys_apps/cli/docker_commands.py
tethys_apps/cli/manage_commands.py

made install scripts more robust
updated docs
cleaned up cli commands fixes

Enhance Install scripts

---

tethys_apps/cli/docker_commands.py

Fix for issue #261. Removed conflicting "already installed" messages.

tethys-261 tethys docker intit -c postgis geoserver 

---

docs/conf.py

Reverts tethysplatform/tethys#293

Revert "RTD Debugging"

---

docs/conf.py
environment_py2.yml

Reverts tethysplatform/tethys#292

Revert "Release"

---

environment_py2.yml

* Fixes `gen settings` command in Windows install script
* Fixes `DOSKEY tstart` command in Windows install script
* Fixes issue with CONDA_HOME in Linux install script when installing Docker
* Temporary fix to resolve `branch` in the docs on Read The Docs

Hotfix 2.0.1

---

docs/conf.py
environment_py2.yml
scripts/install_tethys.bat
scripts/install_tethys.sh
setup.py

* Fixes `DOSKEY tstart` command in Windows install script
* Fixes issue with CONDA_HOME in Linux install script when installing Docker
* Temporary fix to resolve `branch` in the docs on Read The Docs
* bumps version to 2.0.1

Installation Fixes

---

docs/conf.py
environment_py2.yml
scripts/install_tethys.bat
scripts/install_tethys.sh
setup.py

* Fixes `gen settings` command on Windows install script
* Fixes DOSKEY tstart command in Windows install script
* Fixes issue with CONDA_HOME in Linux install script when installing Docker
* Temporary fix to resolve branch in the docs on Read The Docs
* bumps version to 2.0.1

Fix Installation

---

tethys_services/backends/hs_restclient_helper.py
tethys_services/backends/hydroshare.py

This hotfix works on @kjlippold's and my local vms

fix issue 290-hydroshare-oauth

---

tethys_apps/base/app_base.py

Quick fix to handle unset settings. Partially addresses issue #249. A more complete fix will be in a PR on master targeted for release 2.1.

Hotfix/Handle Unset Settings

---

tethys_apps/__init__.py
tethys_apps/app_harvester.py
tethys_apps/base/app_base.py
tethys_apps/cli/gen_templates/settings
tethys_apps/exceptions.py
tethys_apps/management/commands/tethys_app_uninstall.py
tethys_apps/models.py
tethys_apps/static/tethys_apps/css/app_library.css
tethys_apps/templates/tethys_apps/app_library.html
tethys_apps/urls.py
tethys_apps/utilities.py
tethys_apps/views.py

Refactor of app settings and app harvesting to make it more robust (i.e. it won't fail if one app has an error while loading). Also fully handles unconfigured apps in the GUI: only admins will see the apps in the Apps Library, but they will be styled differently and when clicked will go directly to the app settings page (see below).
There are a few impacts that still need to be considered (all marked with TODO comments in the code).

App loading refactor

---

tethys_apps/base/app_base.py

Remove references to get_persistent_store_engine

---

docs/installation/linux_and_mac.rst
scripts/install_tethys.sh

* fixes some bugs related to the new style of conda environments
* provides a default value for the DB initialization step.

install script bugfixes

---

docs/conf.py
docs/installation/linux_and_mac.rst
docs/installation/windows.rst
scripts/install_tethys.bat
scripts/install_tethys.sh
tethys_apps/cli/gen_commands.py
tethys_apps/cli/gen_templates/uwsgi_service
tethys_apps/cli/manage_commands.py
tethys_apps/cli/test_command.py
tethys_apps/utilities.py

Remove hardcoded src directory references.

---

docs/conf.py
docs/docs_environment.yml
readthedocs.yml
setup.py

* mock dependencies.
* install minimum required dependencies for docs build.

Changes to speed up docs build on RTD and prevent timeouts

---

environment_py2.yml
environment_py3.yml
scripts/install_tethys.sh
tests/unit_tests/test_tethys_apps/test_app_installation.py
tests/unit_tests/test_tethys_apps/test_cli/test_cli_colors.py
tests/unit_tests/test_tethys_apps/test_cli/test_docker_commands.py
tests/unit_tests/test_tethys_apps/test_cli/test_scaffold_commands.py
tethys_apps/cli/__init__.py
tethys_apps/cli/cli_colors.py
tethys_apps/cli/docker_commands.py
tethys_apps/cli/gen_commands.py

Hotfix to update the docker client so py3 environment can resolve using 3.6

refactor docker commands to work with latest docker client api

---

environment.yml
scripts/install_tethys.sh
tests/unit_tests/test_tethys_apps/test_app_installation.py
tests/unit_tests/test_tethys_apps/test_cli/test_cli_colors.py
tests/unit_tests/test_tethys_apps/test_cli/test_docker_commands.py
tests/unit_tests/test_tethys_apps/test_cli/test_scaffold_commands.py
tethys_apps/cli/__init__.py
tethys_apps/cli/cli_colors.py
tethys_apps/cli/docker_commands.py
tethys_apps/cli/gen_commands.py

refactor docker commands to work with latest docker client api and fix errors with tethys_src

Docker Update

---

docs/conf.py
docs/tethys_sdk/tethys_services/spatial_dataset_services.rst
tests/unit_tests/test_tethys_compute/test_models/test_CondorBase.py
tests/unit_tests/test_tethys_compute/test_models/test_CondorWorkflow.py
tests/unit_tests/test_tethys_compute/test_models/test_TethysJob.py
tests/unit_tests/test_tethys_compute/test_models/test_dask/test_DaskJob.py
tethys_apps/base/app_base.py
tethys_compute/models/condor/condor_base.py
tethys_compute/models/condor/condor_workflow.py
tethys_compute/models/dask/dask_job.py
tethys_compute/models/tethys_job.py
tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
tethys_gizmos/templates/tethys_gizmos/gizmos/jobs_table.html
tethys_gizmos/views/gizmos/jobs_table.py
tethys_services/backends/hydroshare.py

The jobs table was not updating as it should likely as a result of changes made during the development of the Dask job. The behavior of jobs that were Pending seems to have changed or been fixed. The primary fix in the PR is changing statuses from Pending to Submitted when a job is executed programatically.

Jobs table fix

---

docs/tutorials/getting_started/advanced.rst
tests/unit_tests/test_tethys_gizmos/test_views/test_gizmo_showcase.py
tethys_gizmos/gizmo_options/cesium_map_view.py
tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
tethys_gizmos/templates/tethys_gizmos/gizmos/cesium_map_view.html
tethys_gizmos/views/gizmo_showcase.py

Adds support on the Python end for:
* Globe options
* Clock options
* Use of Cesium constants

Cesium globe clock

---

scripts/install_tethys.sh
setup.py
stable_environment_py2.yml
stable_environment_py3.yml

Fix for issue #436 
Lock posgresql dependency to 11.3 or earlier for release/stable installations.

Hotfix issue 436

---

tethys_gizmos/gizmo_options/map_view.py
tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js

- Adds feature selection to the drawing layer of the MapView.
- Adds data and legend title attributes to the drawing layer of the MapView.

Data and Feature Selection on Drawing Layer.

---

tests/unit_tests/test_tethys_gizmos/test_templatetags/test_tethys_gizmos.py
tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
tethys_gizmos/templatetags/tethys_gizmos.py

Add overview map control to `tethys_map_view`

Overview map

---

tests/unit_tests/test_tethys_gizmos/test_templatetags/test_tethys_gizmos.py
tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
tethys_gizmos/templatetags/tethys_gizmos.py

Fix map view to include overview map control.

Overview map hotfix

---

docs/installation.rst
docs/installation/application.rst
tests/unit_tests/test_tethys_cli/test_db_commands.py
tethys_cli/db_commands.py

db docs fix
db cli windows compatibility

db cli fixes

---

conda.recipe/meta.yaml
tests/unit_tests/__init__.py
tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_bokeh_view.py

Minor fixes for windows compatibility

windows compatibility fixes

---

tethys_cli/db_commands.py

Refactor tethys db configure to create database for superuser

---

Dockerfile
docker/salt/tethyscore.sls
tests/unit_tests/test_tethys_apps/test_base/test_app_base.py
tests/unit_tests/test_tethys_apps/test_harvester.py
tests/unit_tests/test_tethys_cli/test_db_commands.py
tethys_apps/base/app_base.py
tethys_apps/harvester.py

- Add tethys manage.py to docker env
- Updated error/warning message when apps installed before database

Updates to docker, and warning messages

---

Dockerfile

This fixes an issue when building with kaniko

Clean apt-cache before using in Dockerfile

---

docs/index.rst
docs/installation/application.rst
docs/tethys_portal/admin_pages.rst
docs/tethys_sdk/gizmos/jobs_table.rst
docs/whats_new.rst
docs/whats_new/prior_releases.rst

Update whats new for Tethys 3.0

---

stable_environment_py3.yml

the fix suggested in response to Issue #480 and tested by myself and @rfun

Fix django-guardian version

---

docs/tethys_portal/social_auth.rst

Social auth fixes 3.0

---

docs/conf.py
docs/tethys_sdk/extensions/scaffold.rst
docs/tutorials/geoserver/start_and_register.rst
docs/tutorials/getting_started/new_app_project.rst

updated references to python setup.py to new tethys installation

updated docs

---

docs/tethys_portal/social_auth.rst

Hotfix: Updates the documentation for social auth integration.

---

docs/tethys_sdk/templating.rst
docs/tutorials/dask/setup_views.rst
docs/whats_new.rst
docs/whats_new/app_migration.rst
tests/apps/tethysapp-test_app/tethysapp/test_app/templates/test_app/base.html
tests/unit_tests/test_tethys_apps/test_admin.py
tests/unit_tests/test_tethys_apps/test_templatetags/test_tags.py
tethys_apps/admin.py
tethys_apps/base/app_base.py
tethys_apps/templates/tethys_apps/app_base.html
tethys_apps/templates/tethys_apps/app_library.html
tethys_apps/templatetags/tags.py
tethys_cli/scaffold_templates/app_templates/default/tethysapp/+project+/templates/+project+/base.html_tmpl

Bug fixes 2019-10

---

scripts/install_tethys.sh
tests/unit_tests/test_tethys_cli/test_gen_commands.py
tethys_apps/utilities.py
tethys_cli/gen_commands.py
tethys_cli/gen_templates/asgi_service

reconfigure conda environment variables

Fix Production Deployment

---

docs/installation.rst
docs/installation/production/installation.rst

PR #508 merged into production-docs-review. This PR merges into master.
* updated installation docs
* updated installation docs
* updated installation docs

updated installation docs (#508)

---

conda.recipe/meta.yaml
scripts/install_tethys.sh
tethys_cli/gen_templates/portal_config
tethys_gizmos/templatetags/tethys_gizmos.py

workaround fix for the intermittent Django startup errors. Fixes #504

Fix for #504

---

conda.recipe/meta.yaml
docs/installation.rst
docs/installation/production/installation.rst
docs/installation/update.rst
setup.cfg
tethys_cli/gen_templates/metayaml

change conda-package name to be consistent with pip package name

Rename Conda Package

---

.travis.yml
tests/unit_tests/test_tethys_apps/test_management/test_commands/test_collectworkspaces.py
tests/unit_tests/test_tethys_apps/test_utilities.py
tethys_apps/management/commands/collectworkspaces.py
tethys_cli/scaffold_templates/app_templates/default/setup.py_tmpl

* Adds Siphon to default conda recipe
* Changed CI to generate meta.yaml for conda recipe dynamically
* Adds workspaces directories as package data in setup.py of app scaffold
* Modifies the behavior of ``collectworkspaces`` to create workspaces directory for an app if it isn't found.

Dynamic Conda Build and Collect Workspaces Fix

---

docs/conf.py
docs/summary.rst
docs/tethys_portal/configuration.rst
docs/tethys_sdk/templating.rst
docs/tutorials/google_earth_engine.rst
docs/tutorials/google_earth_engine/dataset_controls_js.rst
docs/tutorials/google_earth_engine/plot_data.rst
docs/tutorials/google_earth_engine/vis_gee_layers.rst
docs/tutorials/thredds.rst
docs/tutorials/thredds/plot_at_location.rst
docs/tutorials/thredds/thredds_primer.rst
docs/tutorials/thredds/visualize_leaflet.rst
docs/whats_new.rst
docs/whats_new/app_migration.rst

Various Fixes for the Documentation

---

tests/unit_tests/test_tethys_apps/test_decorators.py
tests/unit_tests/test_tethys_portal/test_views/test_accounts.py
tests/unit_tests/test_tethys_portal/test_views/test_user.py
tethys_apps/decorators.py
tethys_portal/forms.py
tethys_portal/urls.py
tethys_portal/views/accounts.py
tethys_portal/views/user.py

Security hotfix

---

tests/unit_tests/test_tethys_apps/test_decorators.py
tests/unit_tests/test_tethys_portal/test_urls.py
tethys_portal/urls.py

Added tests and fix for #545 - Password Reset URLs without pattern name.

Broken URIs - hotfix

---

tethys_apps/templates/tethys_apps/app_base.html
tethys_apps/templates/tethys_apps/app_library.html
tethys_portal/templates/footer.html
tethys_portal/templates/header.html

Noticed a few issues while trying to run Tethys 3 on a Sub Path in a docker container. The root cause was that we were using hard coded paths for static files and some URLs. This patch fixes those issues. 
@swainn @rileyhales

Use Standard template tags for urls and static files

---

docs/installation/production/app_installation.rst
docs/installation/production/configuration/advanced/social_auth.rst
docs/installation/production/configuration/advanced/webanalytics.rst
docs/installation/production/configuration/basic/file_permissions.rst
docs/installation/production/overview.rst
docs/installation/production/preparation.rst
docs/installation/production/system_dependencies.rst
docs/tutorials/google_earth_engine/part_2/rest_api.rst
docs/tutorials/google_earth_engine/part_3/prepare.rst
docs/tutorials/google_earth_engine/part_3/service_account.rst

Several minor changes to the new production installation documentation based on feedback from NASA.

Production Installation Documentation Fixes

---

docs/installation/production/additional.rst
docs/installation/production/additional/official_docker.rst

There is a build of these docs here:
* http://docs.tethysplatform.org/en/ers6_changes_docs/installation/production/additional/official_docker.html

Docker Official Image Documentation

---

docs/installation/production/additional.rst
docs/installation/production/additional/distributed.rst
docs/installation/production/additional/selinux.rst
docs/installation/production/configuration/advanced/email_config.rst
docs/installation/production/configuration/advanced/webanalytics.rst
docs/installation/production/configuration/basic/database.rst
docs/installation/production/configuration/basic/file_permissions.rst
docs/tethys_portal/configuration.rst

- Broke out SELinux docs from file permissions configuration documentation
- Expanded SELinux docs from my notes for the NASA project
- Added SendGrid example to email configuration
- Updated distributed installation documentation to point to correct docker images
- Fixes various minor typos and discrepencies

Additional Production Documentation

---

docs/installation/production.rst
docs/tutorials/google_earth_engine.rst
docs/tutorials/thredds.rst

- THREDDS tutorial
- Google Earth Engine tutorials
- Production Installation Guide

Add Attribution for NASA

---

.travis.yml
tests/unit_tests/test_tethys_cli/test_docker_commands.py
tethys_cli/docker_commands.py

fix for docker client when docker daemon is not running

---

tests/unit_tests/test_tethys_compute/test_admin.py
tethys_compute/admin.py

Fixes #593 by using password widgets for the Condor Scheduler admin forms.

Fix for #593

---

environment.yml

This is a change to address issue #611

Pin Daphne to 2.5.X

---

docs/installation/production/configuration/advanced/django_channels_layer.rst
docs/installation/production/configuration/advanced/multi_factor_auth.rst
docs/installation/production/configuration/advanced/social_auth.rst
docs/whats_new.rst
docs/whats_new/prior_releases.rst

Updated the What's New page for the 3.2 Release

Update What's New for 3.2 Release

---

tethys_gizmos/templates/tethys_gizmos/gizmos/select_input.html

A very minor change that will allow for customizing the select input html element

added if to select input gizmo form

---

setup.cfg
tethys_gizmos/gizmo_options/jobs_table.py

Hotfix: Jobs Table Bug Fix

---

tests/unit_tests/test_tethys_portal/test_views/test_user.py
tethys_portal/templates/tethys_portal/user/profile.html
tethys_portal/views/user.py

Hotfix for Issue #626.

---

tests/unit_tests/test_tethys_compute/test_models/test_TethysJob.py
tethys_compute/job_manager.py
tethys_compute/models/tethys_job.py
tethys_gizmos/static/tethys_gizmos/js/jobs_table.js

jobs api bugfixes

---

docs/installation/production/configuration/advanced/email_config.rst
docs/installation/production/preparation.rst
docs/tethys_portal/configuration.rst
tests/unit_tests/test_tethys_portal/test_urls.py
tests/unit_tests/test_tethys_portal/test_views/test_accounts.py
tests/unit_tests/test_tethys_portal/test_views/test_email.py
tethys_portal/settings.py
tethys_portal/urls.py
tethys_portal/views/accounts.py
tethys_portal/views/email.py

Email enhancement

---

tests/unit_tests/test_tethys_apps/test_admin.py
tethys_apps/admin.py
tethys_apps/base/app_base.py

Adds the ability to change an app's theme color through the app settings page:

Implements issue #656.

---

tests/unit_tests/test_tethys_apps/test_utilities.py
tethys_apps/utilities.py

* Changed the comparison from comparing names to comparing app_packages.

Fixes issue #653

---

tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
tethys_portal/templates/header.html
tethys_portal/templates/tethys_portal/user/profile.html

Resolves #637
Addresses issue with jobs table incorrectly parsing dates.

Fixes Gravatar and Jobs Table Date Issue

---

tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js

Add check to display cesium geojson point as point instead of billboard.

Add check to display cesium geojson point as point instead of billboard.

---

docs/tethys_portal/admin_pages.rst

Add clarification to App Access Permissions docs

---

tests/unit_tests/test_tethys_cli/test_services_commands.py
tethys_cli/services_commands.py

Fix for #763

---

tests/unit_tests/test_tethys_cli/test_services_commands.py
tethys_cli/services_commands.py

Fix for Spatial Dataset Service created w/ CLI does not work until manually saved in admin pages #763

Fix for #763 Release

---

tests/unit_tests/test_tethys_apps/test_base/test_app_base.py
tethys_apps/base/app_base.py
tethys_apps/urls.py
tethys_gizmos/urls.py
tethys_portal/asgi.py
tethys_portal/urls.py
tethys_services/urls.py

Changes the way that `http_handler_patterns` are routed to allow the ASGI consumers to be called correctly.

fix URL routing for http handler URLS

---

docs/installation/production/cloud.rst
docs/installation/production/docker.rst

Same as PR #769 but adding to the development branch.

Same as PR #769 but to Master

---

tethys_apps/static/tethys_apps/js/app_library.js
tethys_apps/templates/tethys_apps/app_card.html

Hide the app info icon until hover

---

tethys_portal/settings.py

Set appropriate default value for logging configuration

---

tethys_gizmos/gizmo_options/plot_view.py
tethys_gizmos/static/tethys_gizmos/js/plot_view.js

Remove functionReviver from PlotView Gizmo

---

docs/tethys_cli/manage.rst
docs/whats_new.rst
docs/whats_new/prior_releases.rst

Initial what's new page for Tethys 4

---

tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
tethys_portal/dependencies.py

Fixes for issues #810, #811, and #812.

Gizmo showcase map fixes

---

docs/tethys_portal/configuration.rst
tests/unit_tests/test_tethys_portal/test_urls.py
tethys_portal/settings.py
tethys_portal/urls.py

Adds a setting to point the accounts register controller to a custom controller.

Allow a custom register controller

---

docs/conf.py

add social_django.utils to mocked imports
fixes #847

Fix Docs Build

---

tests/unit_tests/test_tethys_apps/test_admin.py
tethys_apps/admin.py

fix 'tethys_quotas.UserQuota' has no ForeignKey error when adding a user through the admin pages
fixes #777

Fix 'tethys_quotas.UserQuota' has no ForeignKey error

---

docs/index.rst
docs/installation/update.rst
docs/installation/update_older.rst
docs/tutorials.rst

Test and update upgrade docs

---

tethys_cli/gen_commands.py
tethys_cli/gen_templates/asgi_service

change asgi gen command to dynamically use the conda env name

Fix gen asgi_service

---

tethys_apps/decorators.py

adjust how the default permission message is handled - fixes #802

fix permission message

---

tests/unit_tests/test_tethys_compute/test_models/test_CondorBase.py
tests/unit_tests/test_tethys_compute/test_models/test_CondorWorkflow.py
tethys_compute/models/condor/condor_base.py
tethys_compute/models/condor/condor_workflow.py
tethys_gizmos/static/tethys_gizmos/css/jobs_table.css
tethys_gizmos/static/tethys_gizmos/js/jobs_table.js
tethys_gizmos/templates/tethys_gizmos/gizmos/job_logs.html
tethys_gizmos/templates/tethys_gizmos/gizmos/workflow_nodes_row.html

Fix condor logs

---

docs/installation/application.rst
tethys_cli/scaffold_templates/app_templates/default/install.yml_tmpl

added tethys_version to install.yml template

Install yml tethys version

---

tests/coverage.cfg
tests/unit_tests/test_tethys_layouts/test_exceptions.py
tests/unit_tests/test_tethys_layouts/test_mixins/test_map_layout.py
tests/unit_tests/test_tethys_layouts/test_views/test_map_layout.py
tests/unit_tests/test_tethys_layouts/test_views/test_tethys_layout.py
tethys_layouts/mixins/map_layout.py
tethys_layouts/views/map_layout.py

Add Tests for the Tethys Layouts Module

---

docs/installation/production/manual.rst
docs/installation/production/manual/additional/backup.rst
docs/installation/production/manual/additional/distributed.rst
docs/installation/production/manual/additional/selinux.rst
docs/installation/production/manual/additional/troubleshooting.rst
docs/installation/production/manual/configuration.rst
docs/installation/production/manual/configuration/advanced/customize.rst
docs/installation/production/manual/configuration/advanced/django_channels_layer.rst
docs/installation/production/manual/configuration/advanced/https_config.rst
docs/installation/production/manual/configuration/basic/database.rst
docs/installation/production/manual/configuration/basic/file_permissions.rst
docs/installation/production/manual/configuration/basic/firewall.rst
docs/installation/production/manual/configuration/basic/nginx.rst
docs/installation/production/manual/configuration/basic/portal_config.rst
docs/installation/production/manual/configuration/basic/static_and_workspaces.rst
docs/installation/production/manual/configuration/basic/supervisor.rst
docs/installation/production/manual/installation.rst
docs/installation/production/manual/overview.rst
docs/installation/production/manual/preparation.rst
docs/installation/production/manual/start_stop.rst
docs/installation/production/manual/system_dependencies.rst
docs/tethys_development.rst
docs/whats_new.rst
tests/unit_tests/test_tethys_cli/test_docker_commands.py
tethys_cli/docker_commands.py
tethys_portal/templates/tethys_portal/home.html

- Various fixes after reviewing the manual production installation for Ubuntu (Note: Did not review CentOS instructions).
- Upgrade `tethys docker` command to pull `postgis/postgis` image instead of `mdillon`

Docs Updates and Bug Fixes

---

.github/workflows/tethys.yml
README.rst
docs/installation/developer_installation.rst
docs/installation/production/docker/dockerfile.rst
docs/installation/production/docker/tethys_docker_reference.rst
docs/tutorials/google_earth_engine/part_3/publish.rst
scripts/install_tethys.sh

Migrate from Master to Main

---

docs/docs_environment.yml

Pin sphinx to fix docs issue

---

docs/installation/production/docker/build.rst
docs/installation/production/docker/docker_compose.rst
docs/installation/production/docker/dockerfile.rst
docs/installation/production/docker/salt_state.rst
docs/installation/production/docker/tethys_docker_reference.rst
docs/tethys_sdk/gizmos/map_view.rst
docs/tethys_sdk/layouts/map_layout.rst
scripts/update_tutorial_tags.py

Updates the Docker Deployment Tutorial for Tethys 4.
Addresses #818

Update the Docker Production Deployment Tutorial for Tethys 4

---

tests/unit_tests/test_tethys_layouts/test_mixins/test_map_layout.py
tethys_layouts/mixins/map_layout.py
tethys_layouts/static/tethys_layouts/map_layout/map_layout.js

Use safe versions of layer_ids for legend ids.

Map Layout Bug Fixes

---

MANIFEST.in
setup.cfg

modify package discovery options to find sub-packages and package data

Fix Packaging Options

---

docs/tethys_sdk/layouts/map_layout.rst
docs/tutorials.rst
docs/tutorials/map_layout.rst
docs/tutorials/map_layout/add_spatial_data.rst
docs/tutorials/map_layout/additional_exercises.rst
docs/tutorials/map_layout/configure_data_plotting.rst
docs/tutorials/map_layout/configure_map_layout.rst
docs/tutorials/map_layout/data_prep.rst
docs/tutorials/map_layout/new_app_project.rst
docs/tutorials/map_layout/resources/add_spatial_data_solution.png
docs/tutorials/map_layout/resources/configure_data_plotting_solution.png
docs/tutorials/map_layout/resources/configure_map_layout_solution.png
docs/tutorials/map_layout/resources/map_layout_app.png
docs/tutorials/map_layout/resources/new_app_project_solution.png
docs/tutorials/map_layout/resources/noaa_digital_logo-2022.png
docs/tutorials/map_layout/resources/popup_example.png
scripts/update_tutorial_tags.py

This tutorial was developed for Map Layout to be used in a Workshop for the 2023 CIROH Training and Developers Conference in Salt Lake City, UT.

Adds rst and png files for Map Layout tutorial

---

tethys_layouts/static/tethys_layouts/map_layout/map_layout.js
tethys_sdk/static/tethys_sdk/js/utilities.js

See #956 
* Fix for WMS feature selection infinite loop
* Remove deprecated Overlay options

Hotfix for #956 - Fix for Feature Selection Hang on MapView Gizmo (#956)

---

tests/unit_tests/test_tethys_apps/test_models/test_TethysApp.py
tethys_apps/models.py

fix sync_settings code to remove last setting

Remove only/all settings

---

docs/tutorials/map_layout.rst

This pull request incorporates several changes to the tutorial based on feedback after the workshop in which it was presented.
* Adds a link to the slideshow that was used during the CIROH Dev conference workshop

Map Layout Tutorial Fixes

---

docs/tethys_sdk/layouts/map_layout.rst
docs/tutorials.rst
docs/tutorials/map_layout.rst
docs/tutorials/map_layout/add_spatial_data.rst
docs/tutorials/map_layout/additional_exercises.rst
docs/tutorials/map_layout/configure_data_plotting.rst
docs/tutorials/map_layout/configure_map_layout.rst
docs/tutorials/map_layout/data_prep.rst
docs/tutorials/map_layout/new_app_project.rst
docs/tutorials/map_layout/resources/add_spatial_data_solution.png
docs/tutorials/map_layout/resources/configure_data_plotting_solution.png
docs/tutorials/map_layout/resources/configure_map_layout_solution.png
docs/tutorials/map_layout/resources/map_layout_app.png
docs/tutorials/map_layout/resources/new_app_project_solution.png
docs/tutorials/map_layout/resources/noaa_digital_logo-2022.png
docs/tutorials/map_layout/resources/popup_example.png
scripts/update_tutorial_tags.py

This PR adds the Map Layout tutorial to the release-4.1 branch in preparation to include in the next 4.1 patch release.

Docs Release - Add Map Layout Tutorial

---

.github/workflows/tethys-release.yml
.github/workflows/tethys.yml
docs/tethys_sdk/layouts/map_layout.rst
scripts/install_tethys.sh
tests/unit_tests/test_tethys_apps/test_models/test_PersistentStoreDatabaseSetting.py
tests/unit_tests/test_tethys_layouts/test_mixins/test_map_layout.py
tethys_apps/base/app_base.py
tethys_layouts/mixins/map_layout.py
tethys_layouts/static/tethys_layouts/map_layout/map_layout.css
tethys_layouts/templates/tethys_layouts/map_layout/map_layout.html
tethys_layouts/views/map_layout.py

- Fix ArcGIS layers in MapLayout and update docs
- Add support for simple legend images via URL
- Fix legend tab overflow/scrolling issue
- Fix linting issues (from previous commits?)

Map layout fixes and improvements

---

tests/unit_tests/test_tethys_layouts/test_mixins/test_map_layout.py
tethys_gizmos/static/tethys_gizmos/js/tethys_map_view.js
tethys_layouts/mixins/map_layout.py

Added label options and updated javascript to display labels alongside normal geometry styles.

Add labeling for geojson features.

---

docs/installation/resources/example-portal-config.yml
docs/tethys_portal/configuration.rst
tests/apps/tethysapp-test_app/tethysapp/test_app/additional_settings.py
tests/unit_tests/test_tethys_portal/test_settings.py
tethys_portal/settings.py

Add the ability to configure additional settings files that will get dynamically loaded into the `tethys_portal.settings.py` file.

Additional Settings Files

---

tests/unit_tests/test_tethys_apps/test_admin.py
tests/unit_tests/test_tethys_apps/test_models/test_ProxyApp.py
tethys_apps/admin.py
tethys_apps/models.py

Fix errors with models on admin pages 

---

.github/pull_request_template.md

This merge request addresses the need for a merge request template.
- Add merge request template
- None
- None

Add Merge Request Template

---

docs/tethys_sdk/paths.rst
docs/tutorials/google_earth_engine/part_2/home_page.rst

This merge request addresses a few typos in documentation pages

Fixing Typos in Documentation

---

tests/unit_tests/test_tethys_gizmos/test_views/test_gizmos/test_jobs_table.py
tethys_gizmos/views/gizmos/jobs_table.py

Async compatibility fixes.
- 
- 
-

Fixes for jobs table async compatibility

---

Dockerfile

update the urls to the salt stack repo 
fixes #1110

Update SaltStack Repos

---

tethys_portal/settings.py

allow custom context processors to be specified in the portal config

Custom Context Processors

---

tethys_cli/start_commands.py

Hotfix: fix quickstart

---

docs/tutorials/thredds/visualize_leaflet.rst

Added some line highlights to code in the THREDDS tutorial to provide clarity

Code Highlights in Tutorial

---

docs/tutorials/thredds/visualize_leaflet.rst

Just a few typo fixes in text and in a code block in the thredds tutorial

Typo FIxes in Thredds Tutorial

---

docs/tutorials/quotas.rst

This pull request includes some updates to the quotas tutorial text and code

Quotas tutorial fix

---

docs/tutorials/google_earth_engine/part_2/about_page.rst
docs/tutorials/google_earth_engine/part_2/clip_by_asset.rst
docs/tutorials/google_earth_engine/part_2/rest_api.rst
docs/tutorials/google_earth_engine/part_3/prepare.rst
docs/tutorials/google_earth_engine/part_3/service_account.rst
docs/tutorials/websockets.rst

Made a few slight adjustments to the web sockets tutorial for clarification and functionality

Web sockets tutorial fix

---

docs/tethys_sdk/gizmos/bokeh_view.rst
tests/unit_tests/test_tethys_gizmos/test_gizmo_options/test_bokeh_view.py
tethys_gizmos/gizmo_options/bokeh_view.py

This merge request addresses failing CI due to bokeh change
- Add a radius to a bokeh circle function.
- N/A
-  Just a test update.

Fix Test After Bokeh Changes

---

docs/_scripts/cleanlinks.py
docs/conf.py
docs/features.rst
docs/installation/production/docker/docker_compose.rst
docs/installation/production/docker/getting_started.rst
docs/installation/production/docker/primer.rst
docs/installation/production/docker/tethys_docker_reference.rst
docs/installation/production/manual/additional/selinux.rst
docs/installation/production/manual/configuration/advanced/social_auth.rst
docs/installation/production/manual/preparation.rst
docs/installation/production/manual/system_dependencies.rst
docs/software_suite.rst
docs/summary.rst
docs/supplementary/app_project.rst
docs/supplementary/key_concepts.rst
docs/tethys_portal/configuration.rst
docs/tethys_sdk/testing.rst
docs/tethys_sdk/tethys_services/persistent_store.rst
docs/tutorials/google_earth_engine/part_2/home_page.rst
docs/tutorials/key_concepts/advanced.rst
scripts/generate_portal_config_tables.py
tests/apps/tethysapp-test_app/tethysapp/test_app/tests/tests.py
tests/extensions/tethysext-test_extension/tethysext/test_extension/tests/tests.py
tethys_gizmos/gizmo_options/cesium_map_view.py
tethys_gizmos/gizmo_options/toggle_switch.py
tethys_portal/settings.py

Fix the rest of the broken links.
- Fixes broken links and redirects in the documentation and doc strings.
- Fixes bugs in the cleanlinks.py helper script
- #1166

Fix broken links 2

---

tests/unit_tests/test_tethys_apps/test_base/test_bokeh_handler.py
tests/unit_tests/test_tethys_apps/test_base/test_mixins.py
tests/unit_tests/test_tethys_apps/test_base/test_paths.py
tests/unit_tests/test_tethys_apps/test_base/test_workspace.py
tests/unit_tests/test_tethys_portal/test_views/test_admin.py
tests/unit_tests/test_tethys_portal/test_views/test_user.py
tethys_apps/base/paths.py
tethys_apps/base/workspace.py
tethys_portal/views/admin.py
tethys_portal/views/user.py

Reverts tethysplatform/tethys#1158

Revert "Quotas bug fix"
